package juno.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BinaryExpression = 0;
  public static final int BooleanLiteral = 1;
  public static final int Comment = 2;
  public static final int EmptyStatement = 3;
  public static final int Expression = 4;
  public static final int Field = 5;
  public static final int FloatLiteral = 6;
  public static final int Int = 7;
  public static final int IntLiteral = 8;
  public static final int Literal = 9;
  public static final int Record = 10;
  public static final int RefinedType = 11;
  public static final int RegexLiteral = 12;
  public static final int Statement = 13;
  public static final int StringLiteral = 14;
  public static final int Type = 15;
  public static final int Workbook = 16;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x4213cd08647045e0L, 0xa4e0f6a4209b6ee6L);
    builder.put(0x5ebaed1a9ccfb6afL, BinaryExpression);
    builder.put(0x5ebaed1a9ccf1064L, BooleanLiteral);
    builder.put(0x5ebaed1a9cd34aeeL, Comment);
    builder.put(0x5ebaed1a9ccf04d4L, EmptyStatement);
    builder.put(0x5ebaed1a9ccca609L, Expression);
    builder.put(0x2673c4abb3c8250eL, Field);
    builder.put(0x5ebaed1a9ccf1065L, FloatLiteral);
    builder.put(0x5ebaed1a9ccca60dL, Int);
    builder.put(0x5ebaed1a9ccca60aL, IntLiteral);
    builder.put(0x5ebaed1a9ccf105fL, Literal);
    builder.put(0x2673c4abb3c7c374L, Record);
    builder.put(0x5ebaed1a9cc54b35L, RefinedType);
    builder.put(0x5ebaed1a9cdcca2bL, RegexLiteral);
    builder.put(0x5ebaed1a9ccccd98L, Statement);
    builder.put(0x5ebaed1a9ccf105dL, StringLiteral);
    builder.put(0x5ebaed1a9cc54b38L, Type);
    builder.put(0x5ebaed1a9ccf049eL, Workbook);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
