package juno.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilder;
import jetbrains.mps.lang.dataFlow.DataFlowBuilderContext;

public class Record_DataFlow extends DataFlowBuilder {
  public void build(final DataFlowBuilderContext _context) {
  }
}
