package juno.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class Field_SubstituteMenu extends SubstituteMenuBase {
  public Field_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for Field. Generated from implicit smart reference attribute.", new SNodePointer("r:348a7849-cae2-4f59-b869-579d38308a9e(juno.structure)", "2770774437497677070")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_cf6pi7_a(), CONCEPTS.Field$48));
    result.add(new SMP_Subconcepts_cf6pi7_b());
    return result;
  }

  public class SMP_ReferenceScope_cf6pi7_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_cf6pi7_a() {
      super(CONCEPTS.Field$48, LINKS.type$1Knv, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_cf6pi7_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_cf6pi7_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "Field", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.Field$48);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Field$48 = MetaAdapterFactory.getConcept(0x4213cd08647045e0L, 0xa4e0f6a4209b6ee6L, 0x2673c4abb3c8250eL, "juno.structure.Field");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink type$1Knv = MetaAdapterFactory.getReferenceLink(0x4213cd08647045e0L, 0xa4e0f6a4209b6ee6L, 0x2673c4abb3c8250eL, 0x5ebaed1a9cc2ff58L, "type");
  }
}
