package juno.editor;

/*Generated by MPS */

import jetbrains.mps.smodel.action.IReferentPresentationProvider;
import juno.behavior.Type__BehaviorDescriptor;

public class PresentationProviders {
  public static final IReferentPresentationProvider PRESENTATION_s65pvt_a0a2a = ((IReferentPresentationProvider) (sourceNode, targetNode) -> Type__BehaviorDescriptor.getId_id5UUVhEsNlFQ.invoke(targetNode));
}
